---
title: ゲームの楽しさを維持する（続き）
actions: ['答え合わせ', 'ヒント']
requireLogin: true
material:
  editor:
    language: javascript
    startingCode:
        "test/CryptoZombies.js": |
            const CryptoZombies = artifacts.require("CryptoZombies");
            const utils = require("./helpers/utils");
            const zombieNames = ["Zombie 1", "Zombie 2"];
            contract("CryptoZombies", (accounts) => {
                let [alice, bob] = accounts;
                let contractInstance;
                beforeEach(async () => {
                    contractInstance = await CryptoZombies.new();
                });
                it("should be able to create a new zombie", async () => {
                    const result = await contractInstance.createRandomZombie(zombieNames[0], {from: alice});
                    assert.equal(result.receipt.status, true);
                    assert.equal(result.logs[0].args.name,zombieNames[0]);
                })
                it("should not allow two zombies", async () => {
                    // start here
                })
            })
        "test/helpers/utils.js": |
            async function shouldThrow(promise) {
              try {
                  await promise;
                 assert(true);
              }
              catch (err) {
                  return;
              }
            assert(false, "The contract did not throw.");

            }

            module.exports = {
              shouldThrow,
            };

    answer: >
        const CryptoZombies = artifacts.require("CryptoZombies");

        const utils = require("./helpers/utils");

        const zombieNames = ["Zombie 1", "Zombie 2"];

        contract("CryptoZombies", (accounts) => {
            let [alice, bob] = accounts;
            let contractInstance;
            beforeEach(async () => {
                contractInstance = await CryptoZombies.new();
            });
            it("should be able to create a new zombie", async () => {
                const result = await contractInstance.createRandomZombie(zombieNames[0], {from: alice});
                assert.equal(result.receipt.status, true);
                assert.equal(result.logs[0].args.name,zombieNames[0]);
            })
            it("should not allow two zombies", async () => {
                await contractInstance.createRandomZombie(zombieNames[0], {from: alice});
                await utils.shouldThrow(contractInstance.createRandomZombie(zombieNames[1], {from: alice}));
            })
        })
---

このチャプターでは、2つ目のテストの中身を埋めていく。やるべきことはこれだ:
- まず、アリスは `createRandomZombie` を呼び、1体目のゾンビに `zombieNames[0]` と名付ける。
- 次に、アリスは2体目のゾンビを生み出そうとする。先ほどと1か所違う点は、ゾンビの名前を `zombieNames[1]` にすることだ。
- この時点で、コントラクトがエラーを `投げて` くれることを我々は期待している。
- スマートコントラクトがエラーを吐くとテストを合格とすることから、ロジックは少し変わってくる。 `createRandomZombie` 関数を2回目に呼び出すときは、 `try/catch` ブロックの中で行うのだ:

```javascript
try {
    // 2体目のゾンビを作成
    await contractInstance.createRandomZombie(zombieNames[1], {from: alice});
    assert(true);
  }
  catch (err) {
    return;
  }
assert(false, "The contract did not throw.");
```
さあ、これで期待通り動くだろうか？

うーむ... あと少しというところだな。

テストコードを整理するため、上記のコードを `helpers/utils.js` に移動し、 “CryptoZombies.js” にインポートする:

```javascript
const utils = require("./helpers/utils");
```

そして、コードの呼び出しはこのようになる:

```javascript
await utils.shouldThrow(myAwesomeContractInstance.myAwesomeFunction());
```

# さあテストだ

前のチャプターで、2つ目のテスト用に空のシェルを作成したな。それを埋めていくぞ。

1. まず、アリスの1体目のゾンビを生み出そう。 `zombieNames[0]` と名づけ、オーナーを渡すことを忘れるなよ。

2. アリスの1体目のゾンビを生み出したら、`shouldThrow` に `createRandomZombie` を引数として渡すんだ。書き方を思い出せなら先ほどの例を見に行け。だがまずは見ずに書いてみることだ。

素晴らしい、2つ目のテストが完成したぞ！

`truffle test` を実行してやったぞ。ここに出力がある:

```bash
Contract: CryptoZombies
    ✓ should be able to create a new zombie (129ms)
    ✓ should not allow two zombies (148ms)


  2 passing (1s)
```

テストに合格した。万歳！
